// Quotes collected from public motivational quote books. Used by motivation.ts.
export const LIBRARY_QUOTES: string[] = [
  "A goal is a dream with a deadline. — Napoleon Hill",
  "A goal properly set is halfway reached. — Zig Ziglar",
  "A good conscience is a continual Christmas. — Benjamin Franklin",
  "A guaranteed way to be miserable is to spend all your time trying to make everyone else happy. — Larry Winget",
  "A man wrapped up in himself makes a very small bundle. — Benjamin Franklin",
  "A mediocre idea that generates enthusiasm will go further than a great idea that inspires no one. — Mary Kay Ash",
  "A strong foundation at home sets you up for a strong foundation at work. — Robin Sharma",
  "Accept the challenges so you can feel the exhilaration of victory. — George S. Patton",
  "Accept your teammates for what they are and inspire them to become all they can be. — Robin Sharma",
  "Act as if what you do makes a difference. It does. — William James",
  "Action is the foundational key to all success. — Pablo Picasso",
  "Aim for the moon. If you miss you may hit a star. — W. Clement Stone",
  "All great thinkers are initially ridiculed - and eventually revered. — Robin Sharma",
  "All of your dreams await just on the other side of your fears. — Grant Cardone",
  "Always choose the future over the past. What do we do now? — Brian Tracy",
  "Always do your best. What you plant now, you will harvest later. — Og Mandino",
  "Always give without remembering and always receive without forgetting. — Brian Tracy",
  "Amateurs sit and wait for inspiration, the rest of us just get up and go to work. — Stephen King",
  "An attitude of a positive expectation is the mark of the superior personality. — Brian Tracy",
  "Anger is never without a reason, but seldom with a good one. — Benjamin Franklin",
  "Any fool can criticize, condemn and complain - and most fools do. — Benjamin Franklin",
  "Any thought or action that you repeat over and over will eventually become a new habit. — Brian Tracy",
  "Arriving at one goal is the starting point to another. — John Dewey",
  "As we each express our natural genius, we all elevate our world. — Robin Sharma",
  "Be gentle to all and stern with yourself. — Saint Teresa of Avila",
  "Be kind whenever possible. It is always possible. — Dalai Lama",
  "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice. — Wayne Dyer",
  "Become a person who would attract the results you seek. — Jim Cathcart",
  "Before you begin scrambling up the ladder of success, make sure that it is leaning against the right building. — Brian Tracy",
  "Being the richest man in the cemetery doesn't matter to me. Going to bed at night saying we've done something wonderful, that's what matters to me. — Steve Jobs",
  "Belief triggers the power to do. — David J. Schwartz",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "Big shots are only little shots who keep shooting. — Christopher Morley",
  "Business is like riding a bicycle. Either you keep moving or you fall down. — Frank Lloyd Wright",
  "By failing to prepare, you are preparing to fail. — Benjamin Franklin",
  "Change is hardest at the beginning, messiest in the middle and best at the end. — Robin Sharma",
  "Clarity precedes mastery. Craft clear and precise plans/goals/deliverables. And then block out all else. — Robin Sharma",
  "Courage is not absence of fear; it is control of fear, mastery of fear. — Mark Twain",
  "Crush your fears with ACTION. — Russell Frazier",
  "Daily exercise is an insurance policy against future illness. The best Leaders Without Titles are the fittest. — Robin Sharma",
  "Discipline is the bridge between goals and accomplishment. — Jim Rohn",
  "Discipline is what you must have to resist the lure of excuses. — Brian Tracy",
  "Do not let what you cannot do interfere with what you can do. — John Wooden",
  "Do or do not. There is no try. — Yoda",
  "Do something wonderful, people may imitate it. — Albert Schweitzer",
  "Do whatever you do intensely. — Robert Henri",
  "Do you want to know who you are? Don't ask. Act! Action will delineate and define you. — Thomas Jefferson",
  "Doing the difficult things that you've never done awakens the talents you never knew you had. — Robin Sharma",
  "Don't be afraid to go out on a limb. That's where the fruit is. — H. Jackson Brown, Jr.",
  "Don't settle for anything less than excellence. — Robin Sharma",
  "Don't be afraid to give up the good to go for the great. — John D. Rockefeller",
  "Don't fight the problem, decide it. — George C. Marshall",
  "Don't give up. Don't lose hope. Don't sell out. — Christopher Reeve",
  "Don't mistake movement for achievement. — Jim Rohn",
  "Don't watch the clock; do what it does. Keep going. — Sam Levenson",
  "Don't wish it were easier, wish you were better. — Jim Rohn",
  "Dream big dreams! Imagine that you have no limitations and then decide what's right before you decide what's possible. — Brian Tracy",
  "Early to bed and early to rise makes a man healthy, wealthy and wise. — Benjamin Franklin",
  "Education is the beginning of transformation. Dedicate yourself to daily learning via books/audios/seminars and coaching. — Robin Sharma",
  "Effective communication is 20% what you know and 80% how you feel about what you know. — Jim Rohn",
  "Either I will find a way, or I will make one. — Philip Sidney",
  "Either move or be moved. — Ezra Pound",
  "Either write something worth reading, or do something worth writing. — Benjamin Franklin",
  "Either you run the day or the day runs you. — Jim Rohn",
  "Energy and persistence conquer all things. — Benjamin Franklin",
  "Even if you fall on your face, you're still moving forward. — Victor Kiam",
  "Ever tried. Ever failed. No matter. Try again. Fail again. Fail better. — Samuel Beckett",
  "Every choice you make has an end result. — Zig Ziglar",
  "Every exit is an entry somewhere else. — Tom Stoppard",
  "Every goal can be achieved if you break it down into enough small parts. — Brian Tracy",
  "Every moment in front of a customer is a gorgeous opportunity to live your values. — Robin Sharma",
  "Every sale has five basic obstacles: no need, no money, no hurry, no desire, no trust. — Zig Ziglar",
  "Every single person in the world could be a genius at something, if they practiced it daily for at least ten years. — Robin Sharma",
  "Everything you do is triggered by an emotion of either desire or fear. — Brian Tracy",
  "Everything you want is on the other side of fear. — Jack Canfield",
  "Everything you've ever wanted is on the other side of fear. — George Addair",
  "Excellence in one area is the beginning of excellence in every area. — Robin Sharma",
  "Excellence is a not a skill. It's an attitude. — Ralph Marston",
  "Expect problems and eat them for breakfast. — Alfred A. Montapert",
  "Failure will never overtake me if my determination to succeed is strong enough. — Og Mandino",
  "Fear and self-doubt have always been the greatest enemies of human potential. — Brian Tracy",
  "Fear doesn't exist anywhere except in the mind. — Dale Carnegie",
  "Fear is 100% dependent on you for its survival. — Steve Maraboli",
  "Fear is the destroyer of dreams and the killer of ambitions. — Jeffrey Benjamin",
  "Focus your mind on the good versus the lack. — Robin Sharma",
  "For every sale you miss because you are too enthusiastic, you will miss a hundred because you are not enthusiastic enough. — Zig Ziglar",
  "Freedom is not something you buy but something you earn. — Grant Cardone",
  "Future intent influences and often determines present actions. — Brian Tracy",
  "Give yourself something to work toward constantly. — Mary Kay Ash",
  "Go out and get busy. — Dale Carnegie",
  "Go the extra mile. There's no one on it! — Grant Cardone",
  "Go where no one's gone and leave a trail of excellence behind you. — Robin Sharma",
  "Goals allow you to control the direction of change in your favor. — Brian Tracy",
  "Goals are the fuel in the furnace of achievement. — Brian Tracy",
  "Great works are performed not by strength but by perseverance. — Samuel Johnson",
  "He that is good at making excuses is seldom good for anything else. — Benjamin Franklin",
  "He that rises late must trot all day. — Benjamin Franklin",
  "High expectations are the key to everything. — Sam Walton",
  "Honesty is the best policy. — Benjamin Franklin",
  "How you think when you lose determines how long it will be until you win. — Gilbert K. Chesterton",
  "I attribute my success to this - I never gave or took any excuse. — Florence Nightingale",
  "I don't look to jump over 7-foot bars; I look for 1-foot bars that I can step over. — Warren Buffet",
  "I never hold grudges; while you're holding a grudge, they're out dancing. — Brian Tracy",
  "I want to put a ding in the universe. — Steve Jobs",
  "I was motivated to be different in part because I was different. — Donna Brazile",
  "I will persist until I succeed. — Og Mandino",
  "I'd rather attempt to do something great and fail than to attempt to do nothing and succeed. — Robert H. Shuller",
  "If it's to be, it's up me! — Brian Tracy",
  "If opportunity doesn't knock, build a door. — Milton Berle",
  "If passion drives you, let reason hold the reins. — Benjamin Franklin",
  "If we all did the things we are capable of doing, we would literally astound ourselves. — Thomas Edison",
  "If you aim at nothing, you will hit it every time. — Tom Cochrane",
  "If you are not taking care of your customer, your competitor will. — Bob Hooey",
  "If you are not willing to risk the usual, you will have to settle for the ordinary. — Jim Rohn",
  "If you aren't going all the way, why go at all? — Joe Namath",
  "If you can get yourself to read 30 minutes a day, you're going to double your income every year. — Brian Tracy",
  "If you desire many things, many things will seem few. — Benjamin Franklin",
  "If YOU don't believe in YOU enough to invest in YOU then don't be surprised when others don't invest in YOU. — Grant Cardone",
  "If you don't see yourself as a winner, you cannot perform as a winner. — Zig Ziglar",
  "If you don't set goals for yourself, you are doomed to achieve the goals of someone else. — Brian Tracy",
  "If you learn from defeat you haven't really lost. — Zig Ziglar",
  "If you really want to do something you'll find a way. If you don't you'll find an excuse. — Jim Rohn",
  "If you want to be successful faster, you must double your rate of failure. — Brian Tracy",
  "If you want to reach a goal, you must see the reaching in your own mind before you actually arrive at your goal. — Zig Ziglar",
  "If you would be loved, love, and be loveable. — Benjamin Franklin",
  "If you're going through hell, keep going. — Winston Churchill",
  "If you're offered a seat of a rocket ship, don't ask what seat! Just get on. — Sheryl Sandberg",
  "In business, it's better to mean a lot to a few rather than a little to many. — Larry Winget",
  "Innovation distinguishes between a leader and a follower. — Steve Jobs",
  "Integrity is what we do, what we say and what we say we do. — Don Galer",
  "Investing energy & resources in yesterday prevents you from creating the future you deserve. — Grant Cardone",
  "Investment in knowledge pays the best interest. — Benjamin Franklin",
  "It ain't over till' it's over. — Yogi Berra",
  "It doesn't matter where you are coming from. All that matters is where you are going. — Brian Tracy",
  "It generally takes about 10 years to become an overnight sensation. — Robin Sharma",
  "It is impossible to succeed without failing. — Brian Tracy",
  "It is not necessary to do extraordinary things to get extraordinary results. — Warren Buffet",
  "It is the working man who is the happy man. It is the idle man who is the miserable man. — Benjamin Franklin",
  "It takes guts to work hard enough to get the things you want. — Cole Bayer",
  "It takes many good deeds to build a good reputation, and only one bad one to lose it. — Benjamin Franklin",
  "It takes more than good intentions to get something done. — Larry Winget",
  "It's easier to prevent bad habits than to break them. — Benjamin Franklin",
  "It's hard to fail, but it is worse never to have tried to succeed. — Theodore Roosevelt",
  "It's not about having the right opportunities, it's about handling the opportunities right. — Mark Hunter",
  "It's not failure itself that holds people back; it is the fear of failure that paralyzes you. — Brian Tracy",
  "Keep your eyes on the stars and your feet on the ground. — Theodore Roosevelt",
  "Knowing what to do and not doing it is the same as not knowing what to do. — Robin Sharma",
  "Lack of direction, not lack of time, is the problem. We all have a twenty-four hour day. — Zig Ziglar",
  "Leaders think and talk about the solutions. Followers think and talk about the problems. — Brian Tracy",
  "Leadership is doing what is right when no one is watching. — George Van Valkenburg",
  "Leadership is the ability to elicit extraordinary performance from ordinary people. — Brian Tracy",
  "Lean in, speak out, have a voice in your organization, and never use the word 'sorry'. — Trish Bertuzzi",
  "Leap, and the net will appear. — John Burroughs",
  "Look for the good in every person in every situation. You'll almost always find it. — Brian Tracy",
  "Lost time is never found again. — Benjamin Franklin",
  "Love me or hate me, at least now you know me. — Grant Cardone",
  "Lucky is where skill meets persistence. — Robin Sharma",
  "Make a customer not a sale. — Katherine Barchetti",
  "Make the work you are doing today better than the work you did yesterday. — Robin Sharma",
  "Make your life matter. — Robin Sharma",
  "Measure your success by your inner scorecard versus an outer one. — Robin Sharma",
  "Money and success demand attention. Ignore either and you will have neither. — Grant Cardone",
  "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all. — Dale Carnegie",
  "Most people think selling is the same as talking. But the most effective salespeople know that listening is the most important part of their job. — Roy Bartell",
  "Motivation is the art of getting people to do what you want them to do because they want to do it. — Dwight D. Eisenhower",
  "Motivation is what gets you started. Habit is what keeps you going. — Jim Rohn",
  "Motivation will almost always beat mere talent. — Norman Ralph Augustine",
  "My dear friend, clear your mind of can't. — Samuel Johnson",
  "Never confuse motion with action. — Benjamin Franklin",
  "Never leave that till tomorrow which you can do today. — Benjamin Franklin",
  "Never leave the site of a strong idea without doing something to execute around it. — Robin Sharma",
  "Never miss a moment to celebrate another. — Robin Sharma",
  "Never miss a moment to encourage someone you work with. — Robin Sharma",
  "Never say anything about yourself you do not want to come true. — Brian Tracy",
  "Never, never, never give up. — Winston Churchill",
  "No bird soars too high if he soars with his own wings. — William Blake",
  "No matter what the level of your ability, you have more potential than you can ever develop in a lifetime. — James T. McCay",
  "No one can make you feel inferior without your consent. — Eleanor Roosevelt",
  "Nobody cares how much you know, until they know how much you care. — Theodore Roosevelt",
  "Nobody counts the number of ads you run; they just remember the impression you make. — William Bernbach",
  "Nobody works better under pressure. They just work faster. — Brian Tracy",
  "Nothing about an excuse can help your situation. — Grant Cardone",
  "Nothing fails like success. Because when you are at the top, it's so easy to stop doing the very things that brought you to the top. — Robin Sharma",
  "On any given Monday I am one sale closer and one idea away from being a millionaire. — Larry D. Turner",
  "One finds limits by pushing them. — Herbert Simon",
  "One of the primary tactics for enduring winning is daily learning. — Robin Sharma",
  "One of the very worst uses of time is to do something very well that need not be done at all. — Brian Tracy",
  "One way to keep momentum going is to have constantly greater goals. — Michael Korda",
  "Only I can change my life. No one can do it for me. — Carol Burnett",
  "Opportunities are usually disguised as hard work, so most people don't recognize them. — Ann Landers",
  "Opportunity doesn't knock, it presents itself when you beat down the door. — Kyle Chandler",
  "Optimism is the one quality associated with success and happiness than any other. — Brian Tracy",
  "Other people's opinions of you are none of your business. — Robin Sharma",
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. — Thomas Edison",
  "Outstanding people have one thing in common: An absolute sense of mission. — Zig Ziglar",
  "Passion + production = performance. — Robin Sharma",
  "Patience is a key element of success. — Bill Gates",
  "Peak performers replace depletion with inspiration on a daily basis. — Robin Sharma",
  "People do business with people who make them feel special. — Robin Sharma",
  "People don't buy for logical reasons. They buy for emotional reasons. — Zig Ziglar",
  "Perseverance is failing 19 times and succeeding the 20th. — Julie Andrews",
  "Perseverance is not a long race; it is many short races one after the other. — Walter Elliot",
  "Pretend that every single person you meet has a sign around his or her beck that says, 'make me feel important.' Not only will you succeed in sales, you will succeed in life. — Mary Kay Ash",
  "Problems are not stop signs, they are guidelines. — Robert H. Shuller",
  "PURPOSE. One word that drives me every day. Find yours and be willing to die for it. — Grant Cardone",
  "Pursue one great decisive aim with force and determination. — Carl von Clausewitz",
  "Quality is not an act, it is a habit. — Aristotle",
  "Quality is pride of workmanship. — W. Edwards Deming",
  "Quality performance starts with a positive attitude. — Jeffrey Gitomer",
  "Rainmakers turn customer objections into customer objectives. — Jeffrey J. Fox",
  "Remember that failure is an event, not a person. Yesterday ended last night. — Zig Ziglar",
  "Remember that leadership is about influence and impact, not title and accolades. — Robin Sharma",
  "Say \"thank you\" when you're grateful and \"sorry\" when you're wrong. — Robin Sharma",
  "Say no to anything that is not a high-value use of your time and your life. — Brian Tracy",
  "Say no to distractions. — Robin Sharma",
  "Saying I'll try really means I'm not really committed. — Robin Sharma",
  "Set no targets & you will get nowhere. — Grant Cardone",
  "Setting goals is the first step in turning invisible into the visible. — Tony Robbins",
  "Shift from being busy to achieving results. — Robin Sharma",
  "Small daily, seemingly insignificant, improvements and innovations lead to staggering achievements over time. — Robin Sharma",
  "Some men see things as they are and ask why... I dream of things that never were and ask why not? — Robert Kennedy",
  "Sometimes life is going to hit you in the head with a brick. Don't lose faith. — Steve Jobs",
  "Speak ill if no man, but speak all the good you know of everybody. — Benjamin Franklin",
  "Speak less. Listen more. — Robin Sharma",
  "Speak softly and carry a big stick; you will go far. — Theodore Roosevelt",
  "Stand for something. Or else you'll fall for anything. — Robin Sharma",
  "Start where you are. Use what you have. Do what you can. — Arthur Ashe",
  "Staying poor is selfish. — Grant Cardone",
  "Step by step and the thing is done. — Charles Atlas",
  "Stop selling. Start Helping. — Zig Ziglar",
  "Success doesn't have any secrets. However, failure's biggest secret is getting you to believe it does. — Larry Winget",
  "Success in life is in direct proportion to what you do after you do what you are expected to do. — Brian Tracy",
  "Success is a full time job. — Grant Cardone",
  "Success is never final. Failure is never fatal. It is courage that counts. — Winston Churchill",
  "Success is nothing more than a few simple disciplines, practiced every day. — Jim Rohn",
  "Success is simple, do what's right, the right way, at the right time. — Arnold H. Glasow",
  "Success is the ability to go from failure to failure without losing your enthusiasm. — Winston Churchill",
  "Success is the culmination of failures, mistakes, false starts, confusion and the determination to keep going anyway. — Nick Gleason",
  "Success lies in a masterful consistency around a few fundamentals. It really is simple. Not easy. But simple. — Robin Sharma",
  "Successful people are always looking for opportunities to help others. — Brian Tracy",
  "Take care of your body. It's the only place you have to live. — Jim Rohn",
  "Take care of your relationships and the sales/money will take care of itself. — Robin Sharma",
  "Take responsibility. Don't blame. Get to work. Everything is up to YOU. — Larry Winget",
  "The act of taking the first step is what separates the winners from the losers. — Brian Tracy",
  "The antidote to stagnation is innovation. — Robin Sharma",
  "The best in business spend far more time on learning than in leisure. — Robin Sharma",
  "The best leaders are the most dedicated learners. Read great books daily. Investing in your self-development is the best investment you will ever make. — Robin Sharma",
  "The best leaders blend courage with compassion. — Robin Sharma",
  "The best leaders lift people up versus tear people down. — Robin Sharma",
  "The best leaders without a title use their heads and listen to their hearts. — Robin Sharma",
  "The best thing you will ever do for yourself is to say goodbye to people who make you less than you could be. — Larry Winget",
  "The bigger the dream, the more important to the team. — Robin Sharma",
  "The Constitution only gives people the right to pursue happiness. You have to catch it yourself. — Benjamin Franklin",
  "The conversations you are most resisting are the conversations you most need to be having. — Robin Sharma",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will. — Vince Lombardi",
  "The difference between try and triumph is just a little umph! — Marvin Phillips",
  "The fears you run from run to you. — Robin Sharma",
  "The few who do are the envy of the many who watch. — Jim Rohn",
  "The great thing in this world is not so much where we stand, as in what direction we are moving. — Oliver Wendell Holmes",
  "The greatest mistake we make is living in constant fear that we will make one. — John Maxwell",
  "The harder the conflict, the more glorious the triumph. — Thomas Paine",
  "The key to success is to focus our conscious mind on things we desire not things we fear. — Brian Tracy",
  "The less you are like others, the less others will like you. — Robin Sharma",
  "The majority of men meet with failure because of their lack of persistence in creating new plans to take the place of those which fail. — Napoleon Hill",
  "The more messes you allow into your life, the more messes will become a normal (and acceptable) part of your life. — Robin Sharma",
  "The more things you do, the more you can do. — Lucille Ball",
  "The more we do, the more we can do. — William Hazlitt",
  "The more you go to your limits, the more your limits will expand. — Robin Sharma",
  "The more you worry about being applauded by others and making money, the less you'll focus on doing the great work that will generate applause. And make you money. — Robin Sharma",
  "The most dangerous place is in your safety zone. — Robin Sharma",
  "The most effective way to do it, is to do it. — Amelia Earhart",
  "The most precious resource for businesspeople is not their time. It's their energy. Manage it well. — Robin Sharma",
  "The most unprofitable item ever manufactured is an excuse. — John Mason",
  "The questions you ask are more important than the things you could ever say. — Tom Freese",
  "The quickest way to grow the sales of your business is to grow your people. — Robin Sharma",
  "The real reward for doing your best work is not the money you make but the leader you become. — Robin Sharma",
  "The road to Easy Street goes through the sewer. — John Madden",
  "The secret of getting ahead is getting started. — Mark Twain",
  "The secret of man's success resides in his insight into the moods of people, and his tact in dealing with them. — J. G. Holland",
  "The secret of passion is purpose. — Robin Sharma",
  "The secret to genius is not genetics but daily practice married with relentless perseverance. — Robin Sharma",
  "The starting point of all achievement is desire. — Napoleon Hill",
  "The successful people are the ones who can think up things for the rest of the world to keep busy at. — Don Marquis",
  "The successful warrior is the average man, with laser-like focus. — Bruce Lee",
  "The things that are hardest to do are often the things that are the best to do. — Robin Sharma",
  "The thoughts you think today determine the results you'll see tomorrow. — Robin Sharma",
  "The value of getting to your goals lives not in reaching the goal but what the talents/strengths/capabilities the journey reveals to you. — Robin Sharma",
  "The way to get started is to quit talking and begin doing. — Walt Disney",
  "There are a thousand excuses for failure but never a good reason. — Mark Twain",
  "There are no traffic jams on the extra mile. — Zig Ziglar",
  "There is always room at the top. — Daniel Webster",
  "There is little success where there is little laughter. — Andrew Carnegie",
  "There never was a truly great man that was not at the same time truly virtuous. — Benjamin Franklin",
  "There's a better way to do it. Find it. — Thomas A. Edison",
  "There's no lotion or potion that will make sales faster an easier for you - unless your potion is hard work. — Jeffrey Gitomer",
  "There's only one direction you can coast. — Brian Tracy",
  "Things do not happen. Things are made to happen. — John F. Kennedy",
  "Things may come true to those who wait, but only the things left by those who hustle. — Unknown",
  "Things turn out best for the people who make the best of the way things turn out. — John Wooden",
  "Think continually about what you want, not about the things you fear. — Brian Tracy",
  "Timid salesmen have skinny kids. — Zig Ziglar",
  "To become successful... Replace IF with WHEN. — Jaden Reichl",
  "To double your net worth, double your self-worth. Because you will never exceed the height of your self-image. — Robin Sharma",
  "To earn more you must learn more. — Brian Tracy",
  "To have everything you want, help as many people as you can possibly find get everything they want. — Robin Sharma",
  "To have the rewards that very few have, do the things that very few people are willing to do. — Robin Sharma",
  "To succeed, jump as quickly at opportunities as you do at conclusions. — Benjamin Franklin",
  "To triple the growth of your organization, triple the growth of your people. — Robin Sharma",
  "Today is always the most productive day of your week. — Mark Hunter",
  "Today the greatest single source of wealth is between your ears. — Brian Tracy",
  "Today's goal: Be nice. Work hard. Tell the truth. Add value. Repeat tomorrow. — Larry Winget",
  "Tough times never last, but tough people do. — Robert H. Schuller",
  "Treat customers as you would your best friend. — Jeffrey J. Fox",
  "Treat people well on your way up and they'll treat you well on your way down. — Robin Sharma",
  "Treating someone as second class never gets you first class results. — David J. Schwartz",
  "Try not to become a person of success, but try to become a person of value. — Albert Einstein",
  "Trying is winning in the moment. — Dan Waldschmidt",
  "Understand that a problem is only a problem if you choose to view it as a problem. — Robin Sharma",
  "Understand the acute difference between the cost of something and the value of something. — Robin Sharma",
  "Visionaries see the \"impossible\" as the inevitable. — Robin Sharma",
  "Wanting something is not enough. You have to be willing to do what it takes to get it. — Larry Winget",
  "We aim above the mark to hit the mark. — Ralph Waldo Emerson",
  "We are all born ignorant, but one must work hard to remain stupid. — Benjamin Franklin",
  "We cannot solve our problems with the same thinking we used when we created them. — Albert Einstein",
  "We heard sheep, we drive cattle, we lead people. Lead me, follow me, or get out of my way. — George S. Patton",
  "We may encounter defeats but we must not be defeated. — Maya Angelou",
  "Well done is better than well said. — Benjamin Franklin",
  "What great thing would you attempt if you knew you could not fail? — Robert H. Shuller",
  "What is called genius is the abundance of life and health. — Henry David Thoreau",
  "What we dwell on is who we become. — Oprah Winfrey",
  "What would life be if we had no courage to attempt anything? — Vincent van Gogh",
  "What you are will show in what you do. — Thomas Edison",
  "What you do today can improve all your tomorrows. — Ralph Marston",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. — Zig Ziglar",
  "What you have done is nothing compared to what you can do. — Grant Cardone",
  "Whatever you are, be a good one. — Abraham Lincoln",
  "Whatever you believe with feeling becomes your reality. — Brian Tracy",
  "When in doubt, don't. — Benjamin Franklin",
  "When obstacles arise, you change your direction to reach your goal; you do not change your decision to get there. — Zig Ziglar",
  "When one must, one can. — Charlotte Whitton",
  "When something is important enough, you do it even if the odds are not in your favor. — Elon Musk",
  "When you believe your mind will find a way to do. — David J. Schwartz",
  "When you know what you want, and you want it bad enough, you'll find a way to get it. — Jim Rohn",
  "When you play, play hard; when you work, don't play at all. — Theodore Roosevelt",
  "Wherever you are - be all there. — Jim Elliot",
  "Who you are becoming is more important than what you are accumulating. — Robin Sharma",
  "Winning isn't everything, but wanting to win is. — Vince Lombardi",
  "Wise men don't need advice. Fools won't take it. — Benjamin Franklin",
  "With a new day comes new strength and new thoughts. — Eleanor Roosevelt",
  "With self-discipline most anything is possible. — Theodore Roosevelt",
  "Without continual growth and progress, such words as improvement, achievement, and success have no meaning. — Benjamin Franklin",
  "Without hard work, nothing grows but weeds. — Gordon B. Hinckley",
  "Words may show a man's wit but actions his meaning. — Benjamin Franklin",
  "Work as if you were to live a hundred years. Pray as if you were to die tomorrow. — Benjamin Franklin",
  "Write injuries in dust, benefits in marble. — Benjamin Franklin",
  "Yesterday ended last night, today is a brand new day and it's yours. — Zig Ziglar",
  "You are fully responsible for everything you are, everything you have, and everything you become. — Brian Tracy",
  "You are not what you think you are, but what you think, you are. — Brian Tracy",
  "You are the average of the five people you spend the most time with. — Jim Rohn",
  "You become what you think about most of the time. — Brian Tracy",
  "You can do anything if you have enthusiasm. — Henry Ford",
  "You can make excuses or you can make progress. You choose. — Brian Tracy",
  "You can't be great if you don't feel great. Make exceptional health your #1 priority. — Robin Sharma",
  "You can't get a good deal from a bad guy. — Larry Winget",
  "You can't help the poor by becoming one of them. — Brian Tracy",
  "You can't wait for inspiration. You have to go after it with a club. — Jack London",
  "You can't build a reputation on what you are going to do. — Henry Ford",
  "You don't close a sale, you open a relationship if you want to build a long-term, successful enterprise. — Patricia Fripp",
  "You don't get more success. You give up the things that are keeping you from being successful. — Larry Winget",
  "You don't have to be great to start but you have to start to be great. — Zig Ziglar",
  "You have to make it happen. — Denis Diderot",
  "You just can't beat the person who never gives up. — Babe Ruth",
  "You may delay, but time will not. — Benjamin Franklin",
  "You miss 100% of the shots you don't take. — Wayne Gretzky",
  "You must take action now that will move you towards your goals. Develop a sense of urgency in your life. — H. Jackson Brown, Jr.",
  "You need to overcome the tug of people against you as you reach for high goals. — George S. Patton",
  "You sleep to rest the body, you wake up to make your dreams a reality. — Grant Cardone",
  "You will get all you want in life if you help enough people get what they want. — Zig Ziglar",
  "You will never find time for anything. If you want time you must make it. — Charles Robert Buxton",
  "You will not have a successful life surrounded by negative people. — Grant Cardone",
  "You'll never go wrong in doing what is right. — Robin Sharma",
  "You'll always get out of life what you put it in - and you control what you put in. — Brian Tracy",
  "Your attitude, not your aptitude, will determine your altitude. — Zig Ziglar",
  "Your behavior will guide the behavior of the other members of your team or the people in your organization. — Brian Tracy",
  "Your competition is everything else your prospect could conceivably spend their money on. — Don Cooper",
  "Your daily schedule reflects your deepest values. — Robin Sharma",
  "Your excuses might be legit but they won't improve your life. — Grant Cardone",
  "Your happiness is up to you. Period. Don't blame someone else because you aren't happy. — Larry Winget",
  "Your heaviest artillery will be your will to live. Keep that big gun going. — Norman Cousins",
  "Your life only gets better when you get better. — Brian Tracy",
  "Your life/finances/relationships/career will be what you make of them. No more. No less. — Larry Winget",
  "Your most unhappy customers are your greatest source of learning. — Bill Gates",
  "Your most valuable asset can be your willingness to persist longer than anyone else. — Brian Tracy",
  "Your results are what they are either because you had a plan or because you didn't have a plan. Which is it? — Larry Winget",
  "A clear vision, backed by definite plans, gives you a tremendous feeling of confidence and personal power. — Brian Tracy",
  "A man is not old until regrets take the place of dreams. — John Barrymore",
  "Great people make you feel that you, too, can become great. — Mark Twain",
  "A soul without a high aim is like a ship without a rudder. — Eileen Caddy",
  "A successful man is one who can lay a firm foundation with the bricks others have thrown at him. — David Brinkley",
  "A superior man is modest in his speech, but exceeds in his actions. — Confucius",
  "Accept responsibility for your life. Know that it is you who will get you where you want to go, no one else. — Les Brown",
  "Achieving life is not the equivalent of avoiding death. — Ayn Rand",
  "Act enthusiastic and you will be enthusiastic. — Dale Carnegie",
  "Action is the antidote to despair. — Joan Baez",
  "Age is a question of mind over matter. If you don't mind, it doesn't matter. — Mark Twain",
  "Age is no guarantee of maturity. — Lawana Blackwell",
  "Aim not for what you are, but for what you could be. — Lucas Hellmer",
  "All religions must be tolerated ... for every man must get to heaven in his own way. — Epictetus",
  "Always do more than is required of you. — George S. Patton",
  "An hour of play discovers more than a year of conversation does. — Portuguese proverb",
  "An optimist sees an opportunity in every calamity. A pessimist sees a calamity in every opportunity. — Winston Churchill",
  "Anger dwells only in the bosom of fools. — Albert Einstein",
  "As long as you live, keep learning how to live. — Lucius Annaeus Seneca",
  "Attitude is a little thing that makes a big difference. — Winston Churchill",
  "Be faithful in small things because it is in them that your strength lies. — Mother Teresa",
  "Be sure that, as you scramble up the ladder of success, it is leaning against the right building. — Stephen Covey",
  "Beauty is the reflection of the magic inside your soul. — Vanessa Hernandez",
  "Become the kind of leader that people would follow voluntarily even if you had no title or position. — Brian Tracy",
  "Champions aren't made in gyms. Champions are made from something they have deep inside them - a desire, a dream, a vision. — Muhammad Ali",
  "Character is the result of two things: mental attitude and the way we spend our time. — Elbert Hubbard",
  "Character, not circumstance, makes the person. — Booker T. Washington",
  "Confidence, like art, never comes from having all the answers; it comes from being open to all the questions. — Earl Gray Stevens",
  "Constant dripping hollows out a stone. — Lucretius",
  "Curiosity is one of the permanent and certain characteristics of a vigorous mind. — Samuel Johnson",
  "Develop a passion for learning. If you do, you will never cease to grow. — Anthony J. D'Angelo",
  "Develop an attitude of gratitude. Say thank you to everyone you meet for everything they do for you. — Brian Tracy",
  "Do we need more time? Or do we need to be more disciplined with the time we have? — Kerry Johnson",
  "Don't compare yourself to others but be inspired by them. — Leo Babauta",
  "Don't count every hour in the day. Make every hour in the day count! — Mark Amend",
  "Emancipate yourselves from mental slavery, none but ourselves can free our minds. — Bob Marley",
  "Empty pockets never held anyone back. Only empty heads and empty hearts can do that. — Norman Vincent Peale",
  "Even if you're on the right track, you'll get run over if you just sit there. — Will Rogers",
  "Excuses are the nails used to build a house of failure. — Don Wilder",
  "Failure should be our teacher, not our undertaker. It is delay, not defeat. It is a temporary detour, not a dead-end street. — William A. Ward",
  "Fear is a priceless education. — Lance Armstrong",
  "For success, attitude is equally as important as ability. — Harry F. Banks",
  "For the real winners, there are no finish lines. — Harvey Mackay",
  "Go for it now. The future is promised to no one. — Wayne Dyer",
  "Good fortune is what happens when opportunity meets with planning. — Thomas Edison",
  "Habit is a cable; we weave a thread of it each day, and at last we cannot break it. — Horace Mann",
  "Happiness lies in the joy of achievement and the thrill of creative effort. — Franklin D. Roosevelt",
  "Hard work made it easy. That is my secret. That is why I win. — Nadia Comaneci",
  "He who angers you conquers you. — Elizabeth Kenny",
  "He who controls others may be powerful, but he who has mastered himself is mightier still. — Lao Tzu",
  "He who lives in harmony with himself lives in harmony with the universe. — Marcus Aurelius",
  "How easy it is to see your brother's faults. How hard it is to face your own. — Buddha",
  "I believe people are in our lives for a reason. We're here to learn from each other. — Gillian Anderson",
  "I can be changed by what happens to me but I refuse to be reduced by it. — Maya Angelou",
  "I know that no one can really stop me but myself and that really no one can help me but myself. — Peter Nivio Zarlenga",
  "I learned that courage was not the absence of fear, but the triumph over it. — Nelson Mandela",
  "I learned that good judgment comes from experience and that experience grows out of mistakes. — Omar Bradley",
  "I'm a great believer in luck, and I find the harder I work the more I have of it. — Thomas Jefferson",
  "If not us, who? If not now, when? — John F. Kennedy",
  "If we cannot end our differences, at least we can help make the world safe for diversity. — John F. Kennedy",
  "If we do not take advantage of our opportunities, it is our own fault. — Thomas J. Watson",
  "If we wait for the moment when everything, absolutely everything is ready, we shall never begin. — Ivan Turgenev",
  "If what you are doing is not moving you towards your goals, then it's moving you away from your goals. — Brian Tracy",
  "If you are a complainer you might have already spent your help quota. — Zig Ziglar",
  "If you can dream it, you can do it. — Walt Disney",
  "If you cannot work with love but only with distaste, it is better that you should leave your work. — Kahlil Gibran",
  "If you change the way you look at things, the things you look at change. — Wayne Dyer",
  "If you don't know what you're after, it's unlikely you're going to find it. — Seth Godin",
  "If you have integrity, nothing else matters. If you don't have integrity, nothing else matters. — Alan K. Simpson",
  "In essence, if we want to direct our lives, we must take control of our consistent actions. — Tony Robbins",
  "It is hard to fail, but it is worse never to have tried to succeed. — Theodore Roosevelt",
  "It is not the mountain that we conquer, but ourselves. — Sir Edmund Hillary",
  "It's all right to have butterflies in your stomach. Just get them to fly in formation! — Dr. Rob Gilbert",
  "It's amazing what ordinary people can do if they set out without preconceived notions. — Charles F. Kettering",
  "It's easy to make a buck. It's a lot tougher to make a difference. — Tom Brokaw",
  "It's not your circumstances that shape you, it's how you react to your circumstances. — Anne Ortlund",
  "It's the most unhappy people who most fear change. — Mignon McLaughlin",
  "Learn how to be happy with what you have while you pursue all that you want. — Jim Rohn",
  "Life is an endless process of self-discovery. — John Gardner",
  "Life is the art of drawing without an eraser. — John Gardner",
  "Life's like a play: it's not the length, but the excellence of the acting that matters. — Lucius Annaeus Seneca",
  "Little minds are tamed and subdued by misfortune; but great minds rise above them. — Washington Irving",
  "Live out of your imagination, not your history. — Stephen Covey",
  "Make what you're doing today important, because you're trading a day of your life for it. — Unknown",
  "Money grows on the tree of persistence. — Japanese Proverb",
  "Most people live, whether physically, intellectually or morally, in a very restricted circle of their potential being. — William James",
  "Never give an order that can't be obeyed. — Douglas MacArthur",
  "No man can think clearly when his fists are clenched. — George Jean Nathan",
  "Nobody stands taller than those willing to stand corrected. — William Safire",
  "Not everything that is faced can be changed, but nothing can be changed until it is faced. — James Baldwin",
  "Nothing focuses the mind better than the constant sight of a competitor who wants to wipe you off the map. — Wayne Calloway",
  "Only those who risk going too far can possibly find out how far they can go. — T.S. Eliot",
  "Our lives begin to end the day we become silent about things that matter. Martin Luther King Jr. Our past is like a footprint. It only confirms we were there. No burden on our future does it bear. — Jeb Dickerson",
  "Peace cannot be kept by force. It can only be achieved by understanding. — Albert Einstein",
  "People rarely succeed unless they have fun in what they are doing. — Dale Carnegie",
  "Persistence is self-discipline in action. — Brian Tracy",
  "Positive thinking will let you do everything better than negative thinking will. — Zig Ziglar",
  "Real love stories never have endings. — Richard Bach",
  "Regardless of who you are or what you have been, you can be what you want to be. — W. Clement Stone",
  "Reputation is for time; character is for eternity. — J. B. Gough",
  "Someday is not a day of the week. — Unknown",
  "Sometimes if you want to see a change for the better, you have to take things into your own hands. — Clint Eastwood",
  "Strength does not come from winning. Your struggles develop your strengths. — Arnold Schwarzenegger",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. — Albert Schweitzer",
  "Successful people are simply those with successful habits. — Brian Tracy",
  "Surround yourself with people strong enough to change your mind. — John Wooden",
  "Tact is the ability to tell someone to go to hell in such a way that they look forward to the trip. — Winston Churchill",
  "The art of teaching is the art of assisting discovery. — Mark Van Doren",
  "The best angle from which to approach any problem is the try-angle. — Unknown",
  "The best way to find yourself is to lose yourself in the service of others. — Mohandas Gandhi",
  "The best way to predict the future is to create it. — Peter Drucker",
  "The big thing is not what happens to us in life - but what we do about what happens to us. — George Allen",
  "The chief cause of failure and unhappiness is trading what we want most for what we want at the moment. — Unknown",
  "The days come and go, but they say nothing. And if we do not use the gifts they bring, they carry them as silently away. — Ralph Waldo Emerson",
  "The greatest discovery of my generation is that a human being can alter his life by altering his attitudes. — William James",
  "The growth of understanding follows an ascending spiral rather than a straight line. — Joanna Field",
  "The men who try to do something and fail are infinitely better than those who try to do nothing and succeed. — Lloyd Jones",
  "The minute you choose to do what you really want to do it's a different kind of life. — Buckminster Fuller",
  "The more difficulties one has to encounter, the higher in inspiration his life will be. — Horace Bushnell",
  "The only limits we have are the limits we believe. — Wayne Dyer",
  "The only place that success comes before work is in the dictionary. — Vidal Sassoon",
  "The only real security that a man will have in this world is a reserve of knowledge, experience & ability. — Henry Ford",
  "The only thing that stands between a person and what they want from life is often the will to try it and the faith to believe it's possible Rich Devos The person without a purpose is like a ship without a rudder. — Thomas Carlyle",
  "The pessimist sees difficulty in every opportunity. The optimist sees the opportunity in every difficulty. — Winston Churchill",
  "The price of success is much lower than the price of failure. — Zig Ziglar",
  "The reason so many people never get anywhere in life is because when opportunity knocks, they are out in the backyard looking for four-leaf clovers. — Walter P. Chrysler",
  "The strength and clarity of your vision will lift you out of the depth of any hardship. — Robin Sharma",
  "The things that are easy to do are also easy not to do. — Jim Rohn",
  "The things which hurt, instruct. — Benjamin Franklin",
  "The trouble with the rat race is that even if you win, you're still a rat. — Lily Tomlin",
  "The true measure of a man is how he treats someone who can do him absolutely no good. — Samuel Johnson",
  "There are no short cuts to any place worth going. — Beverly Sills",
  "There is little difference in people, but that little difference makes a big difference. The little difference is attitude. The big difference is whether it is positive or negative. — W. Clement Stone",
  "There is nothing like dream to create the future. Utopia today, flesh and blood tomorrow. — Victor Hugo",
  "There is nothing so fatal to character as half-finished tasks. — David Lloyd George",
  "There's no point dwelling on what might or could have been. You just have to go forward. — Jack Nicholson",
  "They who give have all things; they who withhold have nothing. — Hindu Proverb",
  "Thinking is the hardest work there is, which is probably the reason so few engage in it. — Henry Ford",
  "This is a wonderful day, I have never seen this one before. — Maya Angelou",
  "To be successful, the first thing to do is fall in love with your work. — Sister Mary Lauretta",
  "To live a creative life, we must lose our fear of being wrong. — Joseph Clinton Pearce",
  "To live without hope is to cease to live. — Fyodor Dostoevsky",
  "To try and fail is at least to learn. To fail to try is to suffer the loss of what might have been. — Benjamin Franklin",
  "True miracles are created by men when they use the courage and intelligence that God gave them. — Jean Anouilh",
  "Turn wounds into wisdom. — Oprah Winfrey",
  "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. — Mark Twain",
  "Very often a change of self is needed more than a change of scene. — Arthur Christopher Benson",
  "We choose our joys and sorrows long before we experience them. — Kahlil Gibran",
  "We could all use a little coaching. When you're playing the game, it's hard to think of everything. — Jim Rohn",
  "We have to dare to be ourselves, however frightening or strange that self may prove to be. — May Sarton",
  "We may affirm absolutely that nothing great in the world has ever been accomplished without passion. — Georg Hegel",
  "We write our own destiny; we become what we do. — Madame Chiang Kai-Shek",
  "What we think determines what happens to us, so if we want to change our lives, we need to stretch our minds. — Wayne Dyer",
  "Whatever we expect with confidence becomes our own self-fulfilling prophecy. — Brian Tracy",
  "When anger rises, think of the consequences. — Confucius",
  "When the power of love overcomes the love of power ... the world will know peace. — Jimi Hendrix",
  "When we direct our thoughts properly, we can control our emotions. — W. Clement Stone",
  "When you are dissatisfied and would like to go back to your youth, think of algebra. — Unknown",
  "When you judge another, you do not define them, you define yourself. — Wayne Dyer",
  "Winners make a habit of manufacturing their own positive expectations in advance of the event. — Brian Tracy",
  "Without a sense of urgency, desire loses its value. — Jim Rohn",
  "You can't expect people to look eye to eye with you if you are looking down on them. — Anonymous",
  "You cannot dream yourself into a character: you must hammer and forge yourself into one. — Henry Thoreau",
  "You have to put in many, many, many tiny efforts that nobody sees or appreciates before you achieve anything worthwhile. — Brian Tracy",
  "You have within you right now, everything you need to deal with whatever the world can throw at you. — Brian Tracy",
  "You never achieve success unless you like what you are doing. — Dale Carnegie",
  "You never truly understand something, until you can explain it to your grandmother. — Albert Einstein",
  "Your belief creates the fact. — James Allen",
  "Your true wealth is the good you do in the world. — Mohammed",
  "A great leader's courage to fulfill his vision comes from passion, not position, John C. Maxwell Always be a first-rate version of yourself, instead of a second-rate version of somebody else. — Judy Garland",
  "Challenges make life interesting, however, overcoming them is what makes life meaningful. — Mark Twain",
  "Defeat is not the worst of failures. Not to have tried is the true failure. — G. Woodberry",
  "I have not failed. I've just found 10,000 ways that won't work. — Thomas Edison",
  "If you expect respect be the first to show it. — Unknown",
  "It is literally true that you can succeed best & quickest by helping others to succeed. — Napoleon Hill",
  "It's a funny thing about life. If you refuse to accept anything but the best, you very often get it. — William Somerset Maugham",
  "Life is like a coin. You can spend it any way you wish, but you only spend it once. — Lillian Dickson",
  "Never look back unless you are planning to go that way. — Henry D. Thoreau",
  "No one heals himself by wounding another. — St. Ambrose",
  "Refuse to be average. Let your heart soar as high as it will. — A. W. Tozer",
  "We all live under the same sky, but we don't all have the same horizon. — Konrad Adenauer",
  "We can only appreciate the miracle of a sunrise if we have waited in the darkness. — Unknown",
  "We have to start teaching ourselves not to be afraid. — William Faulkner",
  "You can never cross the ocean unless you have the courage to lose sight of the shore. — Christopher Columbus",
  "You see things and you say, why? But I dream things that never were and I say, why not? — George Bernard Shaw",
  "Your present circumstances don't determine where you can go; they merely determine where you start. — Nido Qubein",
  "Your willingness to look at your darkness is what empowers you to change. — Iyanla Vanzant",
  "In order to achieve our goals, we have to get a little bit uncomfortable to push beyond those cushy comfort zones. — Clint Cora",
  "We all have the potential for greatness. — Clint Cora",
  "Our biggest competition is never the others. Instead, it is always ourselves. It doesn't matter if we end up with first or last place. If we do our best to do better than before, then we've won. — Clint Cora",
  "When you think you can't... revisit a previous triumph. — Jack Canfield",
  "Sometimes things become possible if we want them bad enough. — T.S. Eliot",
  "Courage is facing your fears. Stupidity is fearing nothing. — Todd Bellemare",
  "Victory is always possible for the person who refuses to stop fighting. — Napoleon Hill",
  "Great works are performed not by strength, but perseverance. — Dr. Samuel Johnson",
  "People become successful the minute they decide to. — Harvey Mackay",
  "Success is predictable. — Brian Tracy",
  "Society may predict, but only I can determine my destiny. — Clair Oliver",
  "There is always a better way. — Thomas Edison",
  "The habit of persistence is the habit of victory. — Herbert Kaufman",
  "People with goals succeed because they know where they are going. — Earl Nightingale",
  "Ambition is the root of all achievement. — James Champy",
  "80% of success is showing up. — Woody Allen",
  "Trust in yourself. Your percep- tions are often far more accurate than you are willing to believe. — Claudia Black",
  "We can do anything we want to if we stick to it long enough. — Helen Keller",
  "Only those who risk going too far can possibly find out how far one can go. — T.S. Eliot",
  "People are anxious to improve their circumstances, but are unwilling to improve themselves. That is why they remain bound. — James Allen",
  "Concentrated thoughts produce desired results. — Zig Ziglar",
  "Genius is divine perseverance. Genius I cannot have, but perseverance all can have. — Woodrow Wilson",
  "Money never starts an idea; it's the idea that starts the money. — Mark Victor Hansen",
  "I am not just here to make a living; I am here to make a life. — Helice Bridges OfF",
  "You may be disappointed if you fail, but you are doomed if you do not try. — Beverly Sills",
  "Success is the prize for those who stand true to their ideas. — John S. Hinds",
  "It's not whether you get knocked down; it's whether you get back up. — Vince Lombardi",
  "Success is neither magical nor mysterious. Success is the natural consequence of consistently applying the basic fundamentals. — Jim Rohn",
  "Believe in yourself and you will be unstoppable. — Emily Guay",
  "He who conquers others is strong. He who conquers himself is mighty. — Lao Tzu",
  "Think BIG! You are going to be thinking anyway, so think BIG! — Donald Trump",
  "Success in the end erases all the mistakes along the way. — Chinese Proverb",
  "The only difference between dreams and achievements is hard work. — Mayor Chris Bollwage",
  "The secret of success is consistency of purpose. — Benjamin Disraeli",
  "If the mind of man can believe, the mind of man can achieve. — Napoleon Hill",
  "To conquer without risk is to triumph without glory. — El Cid",
  "Thoughts and ideas are the source of all wealth, success, material gain, all great discoveries, inventions and achievements. — Mark Victor Hansen",
  "Real success is finding your life work in the work that you love. — David McCullough",
  "Creativity means believing you have greatness. — Dr. Wayne D. Dwyer",
  "I can't believe that God put us on this earth just to be ordinary. — Lou Holtz",
  "In the long run, we only hit what we aim at. — Henry David Thoreau",
  "Believe that you have it, and you will have it. — Latin Proverb",
  "Start each day by affirming peaceful, contented, and happy attitudes and your days will tend to be pleasant and successful. — Norman Vincent Peale",
  "Our aspirations are our possibilities. — Samuel Johnson",
  "Be courageous! Have faith! Go forward. — Thomas A. Edison",
  "This is America.. .we can do anything here! — Ted Turner",
  "Nothing great was ever achieved without enthusiasm. — Ralph Waldo Emerson",
  "Out of difficulties grow miracles. — Jean De La Bruyere",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. — Nelson Mandela",
  "All of our dreams can come true if we have the courage to pursue them. — Walt Disney",
  "IIt's in your moments of decision that your destiny is shaped. — Anthony Robbins",
  "There are no limitations to any of our dreams. — Gene Simmons",
  "Action may not bring happiness, but there is no happiness without action. — William James",
  "If you realized how powerful your thoughts are, you would never think another negative thought. — Peace Pilgrim",
  "Experience tells you what to do. Confidence allows you to do it. — Stan Smith",
  "O- If you consistently and persistently do the things that other successful people do, nothing in the world can stop you from being a big success also. — Brian Tracy",
  "Your ability will grow to match your dreams. — Jim Rohn",
  "Ask yourself, \"Am I now ready to make some changes. — Jack Canfield",
  "Your income rarely exceeds your personal development. — Jim Rohn",
  "A brilliant idea without action is like Mark McGwire playing baseball without a bat. — Jack Canfield",
  "The life that is not examined is not worth living. — Socrates",
  "You've got to get up and work at it to make your dreams come true. — Poh Yu Khing",
  "If I can dream, I can act and if I can act, I can become. — Poh Yu Khing",
  "The only way to discover the limits of the possible is to go beyond them into the impossible. — Arthur C. Clark",
  "Believe you will be successful and you will. — Dale Carnegie",
  "If we always look back, we lose sight of what's ahead. — Justin Sims",
  "You are what you repeatedly do. Excellence is not an event - it is a habit. — Aristotle",
  "Success comes from having dreams that are bigger than your fears. — Terry Litwiller",
  "Some things have to be believed to be seen. — Ralph Hodgson",
  "Things do not change - we change. — Henry David Thoreau",
  "Nothing happens unless first a dream. — Carl Sandberg",
  "Habit is either the best of servants or the worst of masters. — Nathaniel Emmons",
  "Imagination is more important than knowledge. — Albert Einstein",
  "I think, therefore I am. — Rene Descartes",
  "If we did all of the things we are capable of doing, we would literally astound ourselves. — Thomas A. Edison",
  "Wealth is the product of a man's ability to think. — Ayn Rand",
  "Action must be taken at once! There is no time to be lost. — Miguel Hidalgo",
  "Ideas shape the course of history. — John Keynes",
  "To move the world, we must first move ourselves. — Socrates",
  "The great end of life is not knowledge, but action. — Thomas Henry Huxley",
  "I haven't failed; I have just found 10,000 ways that didn't work. — Thomas A. Edison",
  "The secret to success is to be ready when opportunity comes. — Benjamin Disraeli",
  "What the mind dwells upon, the body acts upon. — Thomas Dewar",
  "The world makes way for a man who knows where he is going. — Ralph Waldo Emerson",
  "The only limit of our realization of tomorrow will be our doubts of today. — Franklin D. Roosevelt",
  "He who stops being better, stops being good. — Oliver Cromwell",
  "It is what you learn after you know it all that counts. — John Wooden",
  "The men who succeed are the efficient few. They are the few who have the ambition and will power to develop themselves. — Herbert N. Casson",
  "The difference between the impos- sible and the possible lies in a man's determination. — Tommy Lasorda",
  "Victory belongs to the most persevering. — Napoleon Bonaparte",
  "Man is so made that when anything fires his goal, impossibilities vanish! — Jean De La Fountaine",
  "In each of us there are places we have never gone. Only by pressing the limits do you ever find them. — Dr. Joyce Brothers",
  "Explore, dream, and discover. — Mark Twain",
  "A dream is just a dream. A goal is a dream with a plan and a deadline. — Harvey Mackay",
  "Many people dream of success. To me success can only be achieved through repeated failure and introspection. — Soichiro Honda",
  "People become really quite remarkable when they start thinking that they can do things. When they believe in themselves they have the first secret of success. — Norman Vincent Peale",
  "We do not know who we are until we see what we can do. — Martha Grimes",
  "Life without risk is not worth living. — Charles Lindbergh",
  "If you can dream it, you can make it so. — Belva Davis",
  "Luck is when preparedness meets opportunity. — Earl Nightingale",
  "Hope sees the invisible, feels the intangible, and achieves the impossible. — Charles Caleb Colton",
  "Living never wore one out so much as the effort not to live. — Anais Nin fthA",
  "Do your work with your whole heart, and you will succeed because there is so little competition. — Elbert Hubbard",
  "Life is too short to ponder the \"what if's\" and fear rejection. — T. Dufek",
  "You can get everything you want It is no sin to attempt and fail. if you help enough others The only sin is to not make get what they want. the attempt. — Zig Ziglar",
  "Your current conditions do not When you think big, reflect your ultimate potential. your results are big. — Anthony Robbins",
  "Life is change; growth is optional. Choose wisely. — Karen Kaiser Clark",
  "Everything changes when you change. — Jim Rohn",
  "The best way to cheer yourself up is to cheer everybody else up. — Mark Twain",
  "If MMMMOV I will... until. — Brian Tracy",
  "Dream big dreams. Only big dreams have the power to move men's souls. — Marais Aurelius",
  "I am the captain of my soul. I am the master of my fate. — William Henley",
  "The harder I work, the luckier I get. — James Thurber",
  "Self-discipline is the ability to make yourself do what you should do, when you should do it, whether you feel like it or not. — Elbert Hubbard",
  "In the middle of difficulty lies opportunity. — Albert Einstein",
  "There will never be another now. I will make the most of today. There will never be another me. I will make the most of myself. — Robert H. Schuller",
  "You can't leave footprints in the sands of time if you are sitting on you butt, and who wants to leave buttprints in the sands of time! — Bob Moawad",
  "Relentlessness and discontent are the first necessities of progress. — Thomas A. Edison",
  "Be all that you can be. — ARMY slogan",
  "There is no achievement without goals. — Robert J. McKaine",
  "Be absolutely determined to enjoy what you do. — Gerry Sikorski",
  "Never let the fear of striking out get in your way. — Babe Ruth",
  "Life is too short to be little. — Benjamin Disraeli",
  "This one step, choosing a goal and sticking to it, changes everything. — Scott Reed",
  "You cannot have any success unless you can accept failure. — George Cukor",
  "There is no failure only feedback. — Robert Allen",
  "Failure? I never encountered it. All I ever met were temporary setbacks. — Dottie Walters",
  "The closer one gets to the top, the more one finds that there is no top. — Nancy Barcus",
  "You are successful the moment you start moving toward a worthwhile goal. — Charles Carlson",
  "Learn to listen. Opportunity Great minds have purpose, while sometimes knocks very softly. others just have wishes. — Washington Irving",
  "I am going to succeed. — Dan Dierdorf",
  "Begin with the end in mind. — Stephen Covy",
  "Everyone has a fair turn to be as great as he pleases. — Jeremy Collier",
  "Only those who dare to fail greatly can ever achieve greatly. — Robert Francis Kennedy",
  "Let your heart soar as high as it will. Refuse to be average. — A.W. Tozer",
  "Success is a journey, not a destination. — Ben Sweetland",
  "Success is not permanent, neither is failure. — Dell Crossword",
  "There is no limit to what a man can achieve if he so believes this. — Thomas J. Vilord",
  "Determination is the wake up call to the human will. — Anthony Robbins",
  "The more goals you set, the more goals you get. — Mark Victor Hansen",
  "If God shuts one door, another door opens. — Irish Proverb",
  "We must leave our mark on our life while we have it in our power. — Isak Dinesen",
  "Seek not outside yourself for success lies within. — Mary Lou Cook",
  "Success is the sum of small efforts repeated day in and day out. — Robert Collier",
  "If you want a thing done well, do it yourself. — Napoleon Bonaparte",
  "Great work is done by people who are not afraid to be great. — Fernando Flores",
  "In order to attain the impossible, one must attempt the impossible. — Miguel de Cervantes",
  "The only real failure is the one from which we learn nothing. — John Powell",
  "Difficulties mastered are opportunities won. — Winston Churchill",
  "The first step is to fill your life with positive faith that will help you through anything. The second step is to start where you are. — Norman Vincent Peale",
  "In order to succeed you must fail so you know what to do better the next time. — Anthony D'Angelo",
  "Stumbling is not the same as falling. — Portuguese Proverb",
  "If you can command yourself, you It may seem that those who do can command the world. the most, dream the most. — Chinese Proverb",
  "A wise man makes more opportunities than he finds. — Francis Bacon",
  "Make a success of living by seeing the goal and aiming at it unswervingly. — Cecil B. DeMille",
  "I like the dreams of the future better than the history of the past. — Thomas Jefferson",
  "Every strike brings me closer to the next home run. — Babe Ruth",
  "If anyone else can do it, or make it in life, so can I. — Thomas J. Vilord",
  "Do not let the future be held No one knows what he can do hostage by the past. until he tries. — Neal A. Maxwell",
  "If you believe you can, you probably can. If you believe you won't, you most assuredly won't. Belief is the ignition switch that gets you off the launching pad. — Denis Waitley",
  "Minds are like parachutes - they only function when open. — Thomas Dewar",
  "Happiness is not by chance, but by choice. — Jim Rohn",
  "Success is not final and failure is not fatal. It is the courage to continue that counts. — Winston Churchill",
  "The most important thing is to know that you can do it. — Robert G. Allen",
  "It is the man's dreams and his inspiring attempt to make them come true that remain important. — Francis Ford Coppola",
  "I don't dream at night, I dream all day; I dream for a living. — Steven Spielberg",
  "Nothing is impossible!!! — Norman Vincent Peale",
  "The real secret to success is enthusiasm. — Walter Chrysler",
  "To change one's life we must start immediately and do it flamboyantly. No exceptions. — William James",
  "Beware when God lets loose a thinker on this planet. — Ralph Waldo Emerson",
  "We cannot become what we want to be by remaining what we are. — Max Depree",
  "A person is led on the path that he truly wants to travel on. — The Talmud",
  "The trouble with many plans is that they are based on the way things are now. To be successful, your personal plan must focus on what you want, not what you have. — Nido Qubein",
  "Life is either a daring adventure, or nothing at all. — Helen Keller",
  "Aim for success, not perfection. Never give up your right to be wrong, because then you will lose your ability to learn new things and move forward in your life. — Dr. David M. Burns",
  "You always pass failure on the way to success. — Mickey Rooney",
  "A minute of success pays for years of failure. — Robert Browning",
  "Success is to go from one failure to another with no loss of enthusiasm. — Winston Churchill",
  "You must do the things you think you cannot do. — Elanor Roosevelt",
  "If at first you don't succeed, you are running about average. — M.H. Alderson",
  "It takes twenty years to make an overnight success. — Eddie Cantor",
  "The secret to success in life is for a man to be ready for his opportunity when it comes. — Benjamin Disraeli",
  "Persistentt people begin their success where others end in failure. — Edward Eggleston",
  "The greewwTest happiness is to trraannssftitorm your feelings iiiiinto actions. — Madame de Stael",
  "Coming together is the beginning. Keeping together is progress. Working together is success. — Henry Ford",
  "Champions know that success is inevitable, that there is no such thing as failure, only feedback. They know that the best way to forecast the future is to create it. — Michael J. Gelb",
  "Success isn't magic or hocus-pocus - its simply learning how to focus. — Jack Canfield",
  "The secret of success is this: there is no secret to success. — Elbert Hubbard",
  "I stands a surprised mother-in-law. — Hubert H. Humphrey",
  "It's called perseverance. — Lee Iacocca",
  "Intelligence without ambition is like a bird without wings. — C. Archie Danielson",
  "I wasn't afraid to fail. Something good always comes out of failure. — Anne Baxter",
  "Just like a turtle, we only make progress if we stick our neck out. — James Bryant Conant",
  "We make a living by what we get, but we make a life by what we give. — Winston Churchill",
  "Take heed: you do not find what you do not seek. — English Prover",
  "Many a man has finally succeeded only because he has failed after repeated efforts. If he had never met defeat, he would never have known any great victory. — Orison Swett Marden",
  "Youth is not enough. Love is not enough. Success is not enough. And if we could ever achieve it, enough would not be enough. — Mignon McLaughlin",
  "Success is never wondering what if... — Karrie Huffman",
  "I can't do it\" never accomplished anything; \"I will try\" has performed miracles. — George P. Burnham",
  "Start by doing what is necessary, then what is possible, and suddenly you are doing the impossible. — Francis of Assisi",
  "There are two ways of meeting difficulties: you can alter the difficulties, or you can alter yourself to meet the difficulties. — Phyllis Bottoms",
  "What would you attempt if you knew you could not fail? — Anthony Robbins",
  "If you are not going to think big, don't bother thinking at all. — Thomas J. Vilord",
  "A man can succeed at almost anything for which he has unlimited enthusiasm. — Charles Schwab",
  "A man's dreams are an index to his greatness. — Zadok Rabinowitz",
  "Nothing is hopeless; we must hope for everything. — Madeline L'Engle",
  "You can often measure a man by the size of his dreams. — Robert H. Schuller",
  "The recipe of success is to study while others are sleeping, work while others are loafing, prepare while others are playing, and dream while others are wishing. — William A. Ward",
  "To have more than you've got, become more than you are. — Jim Rohn",
  "I want to seize fate by the throat. — Ludwig van Beethoven",
  "The very essence of leadership is having vision. — Father Theodore Hesburg",
  "The successful man will profit from his mistakes and try again in a different way. — Dale Carnegie",
  "In the marathon of life, success calls for dedication to the goal, perseverance, compassion for my fellow man, and faith in God. — John A. Kelley",
  "Its kind of fun to do the impossible. — Walt Disney",
  "We are what and where we are because we have first imagined it. — Donald Curtis",
  "Hope is not a dream, but a way of making dreams become reality. — Cardinal Sueneus",
  "I Action, to be effective, must be directed to clearly conceived ends. — J. Nehru",
  "Don't let failure get you down. Babe Ruth struck out 1,300 times. — Lou Holtz",
  "Ideas are the beginning of all achievement. — Bruce Lee",
  "Success is the progressive realization of predetermined, worthwhile, personal goals. — Paul Meyer",
  "The game of life is to come up a winner, to be a success, and to achieve what you set out to do. — Richard Nixon",
  "Every achiever that I have ever met says, \"My life turned around when I began to believe in me. — Robert H. Schuller",
  "The real risk is doing nothing. — Denis Waitley",
  "No life ever grows great until it is focused, dedicated, and disciplined. — Henry Emerson Forsdick",
  "If you think you can win, you can win. Faith is necessary for victory. — William Hazlitt",
  "Our real problem is not our strength today; it is rather the vital necessity of action today to ensure our strength tomorrow. — Calvin Coolidge",
  "Set too many goals and keep adding more goals. Goals have a tendency to be realized all at once. — Mark Victor Hansen",
  "It's amazing what ordinary people can do if they set out with preconceived notions. — Charles F. Kettering",
  "Except and expect positive things, and that is what you will receive. — Lori Hard",
  "Procrastination is the seed of self-destruction. — Matthew Burton",
  "Success is not all about money. It's about having the resources and the ability to live the life that you have personally dreamed of. — Pete Zafra",
  "If you don't think everyday is a great day, try going without one. — Jim Evans",
  "To learn, you have to listen. To improve, you have to try. — Thomas Jefferson",
  "One of the most important princi- ples of success is developing the habit of going the extra mile. — Napoleon Hill",
  "If you can dream it, you can do it. Your limits are all within yourself. — Brian Tracy",
  "A winner never stops trying. — Tom Landry",
  "The three P's of success: Passion, Persistence, and Patience. — Doug Bronson",
  "Better is not something you wish, it is something you become. — Jim Rohn",
  "True success is overcoming the fear of being unsuccessful. — Paul Sweeney",
  "If you are successful, you may win false friends and true enemies. Succeed anyway. — Mother Theresa",
  "What distinguishes us from one another is our dreams, and what we do to make them come about. — Joseph Epstein",
  "The spirit, the will to win, and the will to excel are the things that endure. These qualities are so much more important than the events that occur. — Vince Lombardi",
  "Accept the past for what it was. Acknowledge the present for what it is. Anticipate the future for what it can become. — Tracy L. McNair",
  "I have tried 99 times and have failed, but on the 100th time came success. — Albert Einstein",
  "Anyone who has never made a mistake has never tried anything new. — Albert Einstien",
  "Without ambition no conquests are made, and no business created. Ambition is the root of all achievement. — James Champy",
  "Cause change and lead; accept change and survive; resist change and die. — Ray Norda",
  "Some men give up their designs when they have almost reached their goal, while others obtain a victory by exert- ing, at the last moment, more vigorous efforts than ever before. — Herodotusv",
  "I would rather fail in a cause that would ultimately succeed, than succeed in a cause that would ultimately fail. — Woodrow Wilson",
  "Of Success is neither magical nor mysterious. Success is the natural consequence of consistently applying the basic fundamentals. — Jim Rohn",
  "I know the price of success: dedication, hard work, and an unremitting devotion to the things you want to see happen. — Frank Lloyd Wright",
  "I do believe I am special. My special gift is my vision, my commitment, and my willingness to do whatever it takes. — Anthony Robbins",
  "Success is a piece of mind which is a direct result of the self-satisfaction knowing you did your best to become the best you are capable of becoming. — John Wooden",
  "No man ever became great without many and great mistakes. — William E. Gladstone",
  "I do not think there is any other quality so essential to success of any kind as the quality of perseverance. It overcomes almost everything, even nature. — John D. Rockefeller",
  "If you want your life to be a magnificent story, then begin by realiz- ing that you are the author and everyday you have the opportunity to write a new page. — Mark Houlahan",
  "Why? Why not? Why not you? Why not now? — Aslan",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. — Ralph Waldo Emerson",
  "We must all suffer one of two things: The pain of discipline or the pain of regret and disappointment. — Jim Rohn",
  "Through perseverance, many people win success out of what seemed destined to be certain failure. — Benjamin Disraeli",
  "To be successful you must decide exactly what you want to accomplish, and then resolve to pay the price to get it. — Bunker Hunt",
  "Success is not where you are in life, but the obstacles you have overcome. — Booker T. Washington",
  "I know of rto more encouraging fact than the unquestionable ability of ma n to elevate his life by con scious effort. — I Henry David Thoreau N",
  "I' PI Man alone has the power to transfer his thoughts into physical reality; man alone can dream and make his dreams come true. — Napoleon Hill",
  "0.. Success never comes to look for you while you wait around. You've got to get up and work at it to make your dreams come true. — Poh Yu Khing",
  "To the world you may be one person, but to one person you may be the world. — Paulette Mitchell .F",
  "A time comes when you need to stop waiting for the man you want to become and start being the main you want to be. — Bruce Springsteen ft 'I",
  "Ofk We will either find a way or make one. — Hannibal",
  "Hold yourself to a higher standard than anybody else expects of you. — Henry Ward Beecher",
  "The history of the world is the history of a few men who had faith in themselves. That faith calls out the divinity within. You can do anything! — Swami Vivekananda",
  "Exceed expectations. We are not driven to do extraordinary things, but to do ordinary things extraordinarily well. — Bishop Gore",
  "Practice is just as valuable as a sale. The sale will make you a living; the skill will make you a fortune. — Jim Rohn",
  "Show me someone who has done something worthwhile, and I'll show you someone who has overcome adversity. — Lou Holtz",
  "Our limitations and success will be based most often on our own expectations for ourselves. What the mind dwells upon, the body acts upon. — Thomas Dewar",
  "You may have a fresh start at any moment you choose, for this thing we call \"failure\" is not falling down, but staying down. — Mary Pickford",
  "We must walk consciously only part way toward our goal, and then leap into the dark to our success. — Henry David Thoreau",
  "The pessimist sees difficulty in every opportunity; an optimist sees the opportunity in every difficulty. — Winston Churchill",
  "If what you did yesterday seems big, you haven't done anything today. — Lou Holtz",
  "Courage is not the absence of fear, but rather the judgment that something else is more important than one's fear. — Ambrose Redmoon",
  "In reading the lives of great men, I found that the first victory they won were over themselves... self-discipline with all of them came first. — Harry S. Truman",
  "Obstacles are those frightful things you see when you take your eyes off you goal. — Henry Ford",
  "We cannot discover new oceans until we have the courage to lose sight of the shore. — Muriel Chen",
  "J It seems to me that we can never give up longing and wishing while we are alive. There are certain things we feel to be beautiful and good, and we must hunger for them always. — George Eliot",
  "J-M If you are not happy every morning when you get up, leave for work, or start to work at home, and are not enthusiastic about doing that, you will not be successful. — Donald M. Kendall",
  "PI Life is too short to ponder the \"what if's\" and fear rejection. — T. Dufek",
  "You can get everything you want if you help enough others get what they want. — Zig Ziglar",
  "You don't have to be great to get started, but you have to get started to be great. — Les Brown",
  "MMMMOV I will... until. — Brian Tracy",
  "The law of cause and effect: If you do what other successful people do, you will eventually get the results that other successful people get. — Brian Tracy",
  "A person with a clear purpose will make progress on even the roughest road. A person with no purpose will make no progress even on the smoothest road. — Thomas Carlyle",
  "Continuous learning is the minimum requirement for success in any field! — Denis Waitley",
  "OF I must create a system, or be enslaved in another man's. I will not reason and compare; my business is to create. — William Blake",
  "Don't start the day until you have it finished. Don't start the week until you have it finished. Don't start the month until you have it finished. Plan your day. — Jim Rohn",
  "You don't just stumble into the future; you create your own future. — Roger Smith",
  "Great minds have purpose, while others just have wishes. — Washington Irving",
  "Decide what you want, and decide what you are willing to exchange for it. Establish your priorities and go to work. — H.L. Hunt",
  "The more you seek security, the less of it you have. The more you seek opportunity, the more likely it will be that you will achieve the security you desire. — Brian Tracy",
  "I believe that the road to pre-eminent success in any line of work is to make yourself master of that line of work. — Andrew Carnegie",
  "Today is the best preparation for what tomorrow may bring. I, The first step is to fill your life with positive faith that will help you through anything. The second step is to start where you are. — Norman Vincent Peale",
  "Success depends upon our previous preparations, and without such preparations there is sure to be failure. — Confucius",
  "Look to today. Procrastination is the art of keeping up with yesterday. — Don Marquis",
  "0*# The major reason for setting a goal is for what it makes of you to accomplish it. What it makes of you will always be the far greater value than what you get. — Jim Rohn",
  "What counts is not necessarily the size of the dog in the fight, but the size of the fight in the dog. — General Dwight Eisenhower",
  "If you are truly flexible and go until.. .there is very little you can't accomplish in your lifetime. — Anthony Robbins",
  "Success as I see it is a result, not a goal. — Gustave Flaubert",
  "A man is a success if he gets up in the morning and goes to bed at night, and in between does what he wants to do. — Bob Dylan",
  "You can change all things for the better when you change yourself for the better. — Jim Rohn",
  "The truth is that all of us can attain the greatest success and happiness possible in this life whenever we use our native capacities to its greatest extent. — Smiley Blanton",
  "Nature gave us two ends: one to sit on and one to think with. Ever since then, man's success or failure has been dependent on the one he used most. — Robert Albert Bloch.",
  "The first and mo,st important step toward success is the feeling that we can! succeed. — Nelson Boswell",
  "Nobody succeeds beyond his or her wildest expectations unless he or she begins with some wild expectations. — Ralph Charell",
  "L A' If I had permitted myv failures, or what seemed to me at the time a lack of success, to discourage me, I cannot see any way in which I would have ever made progress. — Calvin Coolidge",
  "I don't know the key to success, but the key to failure is trying to please everybody. — Bill Cosby",
  "Failure is instructive. The person who really thinks, learns just as much from his failures as he does from his successes. — John Dewey",
  "To succeed you need to find something to hold onto, something to motivate you, and something to inspire you. — Tony Dorsett",
  "Working hard overcomes a whole lot of other obstacles. You can have unbelievable intelligence, you can have connections, and you can have opportunities fall out of the sky. But in the end, hard work is the true, enduring characteristic of successful people. — Marsha Evans",
  "Our belief at the beginning of a doubtful undertaking is the one thing that assures the successful outcome of any venture. — William James",
  "IBehind every successful man I stands a surprised mother-in-law. — Hubert H. Humphrey",
  "You've got to say, \"I think that if I keep working at this and want it badly enough, I can have it.\" It's called perseverance. — Lee Iacocca",
  "O# The difference between a successful person and the others is not a lack of strength and not a lack of knowledge, but a lack of will. — Vince Lombardi",
  "Failing to plan is planning to fail. — Effie Jones",
  "00K It is a fabulous country, the only fabulous country; it is the only place where miracles not only happen, but they happen all of the time. — Thomas Wolf",
  "Don't limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, you can achieve! — Mary Kay Ash",
  "Believe in yourself! Have faith in your abilities! Without a humble, but reasonable confidence in your own powers, you cannot be successful or happy. — Norman Vincent Peale",
  "Remove failure as an option. — Joan Lunden",
  "Far better is it to dare mighty things to win glorious triumphs, even though checkered with failure, than to make rank with those poor spirits who neither enjoy much nor suffer much, because they live in the gray twilight that knows not victory or defeat. — Theodore Roosevelt",
  "Men succeed when they realize that their failures are the preparation for their victories. — Ralph Waldo Emerson",
  "There isn't a person anywhere that isn't capable of doing more than he thinks he can. — Henry Ford",
  "What we must decide is how we are valuable, rather than how valuable we are. — F. Scott Fitzgerald",
  "IfI The uncommon man is merely the common man thinking and dreaming of success in larger terms and in more fruitful areas. — Melvin Powers",
  "Success is doing what you want to do, when you want, with whomever you want, as much as you want. — Anthony Robbins",
  "The only way to excellence is to consistently improve yourself every single day. — Thomas J. Vilord A'",
  "Our life is what our thoughts make it. Do the best that you can, where you are, with what you have. — Marcus Aurelius",
  "Happiness doesn't depend on what we have, but it does depend on how we feel toward what we have. We can be happy with little and miserable with much. — William Dempster Hoard",
  "Success has always been easy to Emeasure. It's the distance between one's origins and one's final achievement. — Michael Korda 'N",
  "I have had dreams and I have had nightmares. I overcame my nightmares because of my dreams. — Jonas Salk",
  "Every great work, every great accomplishment, has been brought into manifestation through holding to the vision, and often comes apparent and temporary failure and discouragement just before the big achievement. — Florence Scovel Shinn",
  "The achievement of your goal is assured the moment you commit yourself to it! — Mark R. Douglas",
  "The reason most people never reach their goals is because they do not define them, or even seriously consider them as believable or achievable. Winners can tell you where they are going, what they plan to do along the way, and who will be sharing the adventure with them. — Denis Waitley",
  "You can have anything you N want if you want it badly enough. You can be anything you want to be, do anything you set out to accomplish if you hold to that desire with singleness of purpose. — William Adams . . .. .",
  "Optimism is essential to achievement and it is also the foundation of courage and true progress. — Lloyd Alexander",
  "There are two things to aim at in life: first, to get what you want and second is to enjoy it. Only the wisest of mankind achieve the second. — Logan Pearsall Smith",
  "If you can imagine it, you can achieve it; if you can dream it, you can become it. — William Arthur Ward",
  "Time is our most valuable asset, yet we tend to waste it, kill it, and spend it rather than invest it. — Jim Rohn",
  "The meeting of preparation with opportunity generates the offspring we call luck. — Anthony Robbins",
  "We must have courage to bet on our ideas, take the calculated risk, and take action! — Martin Brown",
  "Winners must have two things: definite goals, and a burning desire to achieve them. — Brad Burden"
];
